{
 "title": "csgo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "info",
   "type": "text",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 0 },
   "content": "## server aliases\nadd these to your autoexec to type `pug` or `dm` to connect to that server\n\n```\npassword tbcuk2012\nalias dm connect dm.rdkr.uk\nalias pug connect pug.rdkr.uk\n```\n\n## binds\nadd these to your autoexec to hold `q` to noclip and to jumpthrow with `alt`\n\n```\n// noclip toggle\nalias +noclip \"noclip\"\nalias -noclip \"noclip\"\nbind \"q\" \"+noclip\"\n\n// jumpthrow bind\nalias \"+jumpthrow\" \"+jump;-attack\"\nalias \"-jumpthrow\" \"-jump\"\nbind \"ALT\" \"+jumpthrow\"\n```\n\n## rates\nadd these to your autoexec to ensure 128 tick rates where possible\n\n```\n// rates\ncl_interp \"0\"\ncl_interp_ratio \"1\"\ncl_cmdrate \"128\"\ncl_updaterate \"128\"\nrate \"128000\"\n```"
  },
  {
   "title": "game times",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "content": "## confirmed game times\n* friday 24th, 1730-1900\n* saturday 25th, 1700-1900\n\n## potential game times\n* saturday 25th, day time, all generally available. please dm times\n* sunday 26th, any time, jon not available but pete has a ringer. please dm times"
  },
  {
   "title": "pug game version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "csgo_version{name=\"pug\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "dm game version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "csgo_version{name=\"dm\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ping",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "csgo_ping != -1", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "players",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "csgo_player_count != -1", "legendFormat": "{{name}}" }
   ]
  }
 ]
}