#cloud-config 

fqdn: cs.rdkr.uk
hostname: cs.rdkr.uk

mounts:
  - [sda, /mnt]

users:
  - name: csgo
    lock_passwd: True
    homedir: /mnt/csgo
    shell: /bin/bash

package_upgrade: true

write_files:
  - owner: root:root
    path: /etc/systemd/system/csgo.service
    content: |
      [Unit]
      Description=csgo
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      Type=forking
      User=csgo
      WorkingDirectory=/mnt/csgo
      ExecStart=/mnt/csgo/csgoserver start
      ExecStop=/mnt/csgo/csgoserver stop
      Restart=no
      RemainAfterExit=yes
      
      [Install]
      WantedBy=multi-user.target

  - owner: root:root
    path: /root/csgoserver.cfg
    content: |
      #### Game Server Settings ####

      ## Server Start Settings | https://docs.linuxgsm.com/configuration/start-parameters
      # https://docs.linuxgsm.com/game-servers/counter-strike-global-offensive
      
      gamemode="1"
      mapgroup="mg_active"
      defaultmap="de_mirage"

      maxplayers="10"
      tickrate="128"

      gslt="${srcds_token}"

      ## Workshop Parameters | https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators
      # To get an API key visit - https://steamcommunity.com/dev/apikey
      wsapikey="${workshop_token}"
      wscollectionid=""
      wsstartmap=""

runcmd:
  - 'echo steamcmd steamcmd/question select "I AGREE" | sudo debconf-set-selections'
  - 'echo steamcmd steamcmd/license note '' | sudo debconf-set-selections'
  - 'dpkg --add-architecture i386'
  - 'apt update'
  - 'apt install -y netcat curl wget file tar bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 lib32stdc++6 steamcmd'
  - 'echo "ip=$(curl http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/address)" >> /root/csgoserver.cfg'
  - 'cp /root/csgoserver.cfg /mnt/csgo/lgsm/config-lgsm/csgoserver/csgoserver.cfg'
  - 'chown -R csgo:csgo /mnt/csgo'
  - 'systemctl enable csgo'
  - 'systemctl start csgo'