## template: jinja
#cloud-config 

fqdn: cs.rdkr.uk
hostname: cs.rdkr.uk

mounts:
  - [sda, /mnt]

users:
  - name: csgo
    homedir: /mnt/csgo
    lock_passwd: True
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

package_upgrade: true

write_files:
  - path: /etc/systemd/system/csgo.service
    owner: root:root
    content: |
      [Unit]
      Description=csgo
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      Type=forking
      User=csgo
      WorkingDirectory=/mnt/csgo
      ExecStart=/mnt/csgo/csgoserver start
      ExecStop=/mnt/csgo/csgoserver stop
      Restart=no
      RemainAfterExit=yes
      
      [Install]
      WantedBy=multi-user.target

  - path: /etc/cron.d/csgo
    owner: root:root
    content: |
      * * * * * csgo wget -O /mnt/csgo/serverfiles/csgo/cfg/server.cfg https://raw.githubusercontent.com/rdkr/infra/master/csgo/server.cfg > /dev/null
      * * * * * csgo wget -O /mnt/csgo/serverfiles/csgo/addons/sourcemod/configs/admins_simple.ini https://raw.githubusercontent.com/rdkr/infra/master/csgo/admins_simple.ini > /dev/null
      * * * * * csgo wget -O serverfiles/csgo/addons/sourcemod/configs/deathmatch/deathmatch.ini https://raw.githubusercontent.com/rdkr/infra/master/csgo/deathmatch.ini > /dev/null
      * * * * * csgo wget -O serverfiles/csgo/addons/sourcemod/configs/adminmenu_cfgs.txt https://raw.githubusercontent.com/rdkr/infra/master/csgo/adminmenu_cfgs.txt > /dev/null
      * * * * * csgo wget -O serverfiles/csgo/cfg/sourcemod/map-cfg/aim_.cfg https://raw.githubusercontent.com/rdkr/infra/master/csgo/aim_.cfg
      * * * * * csgo ./csgoserver monitor > /dev/null

  - path: /root/lgsm.cfg
    owner: root:root
    content: |
      
      ip={{ ds.meta_data.interfaces.public[0].ipv4.ip_address }}
      
      gametype="0"
      gamemode="1"

      mapgroup=""
      defaultmap=""

      maxplayers="10"
      tickrate="128"

      gslt="${csgo_gslt_token}"

      wsapikey="${csgo_web_token}"
      wscollectionid=""
      wsstartmap=""

      updateonstart="on"

  - path: /root/csgoserver.cfg
    owner: root:root
    content: |
      rcon_password "${csgo_rcon_password}"
      hostname "cs.rdkr.uk"
      bot_kick
      mp_endmatch_votenextmap 0

runcmd:
  - su - csgo -c """wget --no-clobber -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh csgoserver"""
  - su - csgo -c """./csgoserver auto-install"""
  - cp /root/lgsm.cfg /mnt/csgo/lgsm/config-lgsm/csgoserver/csgoserver.cfg
  - cp /root/csgoserver.cfg /mnt/csgo/serverfiles/csgo/cfg/csgoserver.cfg
  - chown -R csgo:csgo /mnt/csgo
  - systemctl enable csgo
  - systemctl start csgo
