#cloud-config

users:
  - name: csgo
    lock_passwd: True
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

package_upgrade: true

write_files:
  - path: /etc/systemd/system/csgo.service
    owner: root:root
    content: |
      [Unit]
      Description=csgo
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=forking
      User=csgo
      WorkingDirectory=/home/csgo
      ExecStartPre=/home/csgo/pre-start.sh
      ExecStart=/home/csgo/csgoserver start
      ExecStop=/home/csgo/csgoserver stop
      TimeoutStartSec=infinity
      Restart=no
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
