## template: jinja
#cloud-config 

fqdn: dm.rdkr.uk
hostname: dm.rdkr.uk

mounts:
  - [sda, /mnt]

users:
  - name: csgo
    homedir: /mnt/csgo
    lock_passwd: True
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

package_upgrade: true

write_files:
  - path: /etc/systemd/system/csgo.service
    owner: root:root
    content: |
      [Unit]
      Description=csgo
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      Type=forking
      User=csgo
      WorkingDirectory=/mnt/csgo
      ExecStartPre=/mnt/csgo/pre-start.sh
      ExecStart=/mnt/csgo/csgoserver start
      ExecStop=/mnt/csgo/csgoserver stop
      Restart=no
      RemainAfterExit=yes
      
      [Install]
      WantedBy=multi-user.target

  - path: /root/pre-start.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/env sh

      wget -nc https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git971-linux.tar.gz
      tar xfv mmsource-1.10.7-git971-linux.tar.gz -C serverfiles/csgo

      wget -nc https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6482-linux.tar.gz
      tar xfv sourcemod-1.10.0-git6482-linux.tar.gz -C serverfiles/csgo

      mv serverfiles/csgo/addons/sourcemod/plugins/nextmap.smx serverfiles/csgo/addons/sourcemod/plugins/disabled/
      mv serverfiles/csgo/addons/sourcemod/plugins/fun* serverfiles/csgo/addons/sourcemod/plugins/disabled

      wget -nc https://github.com/Maxximou5/csgo-deathmatch/releases/download/v2.0.9/deathmatch.zip
      unzip deathmatch.zip -d serverfiles/csgo/addons/sourcemod

      csgo=/mnt/csgo/serverfiles/csgo
      github=https://raw.githubusercontent.com/rdkr/infra/master/csgo

      wget -O $${csgo}/gamemode_competitive_server.cfg $${github}/dm/gamemode_competitive_server.cfg
      wget -O $${csgo}/addons/sourcemod/configs/admins_simple.ini $${github}/admins_simple.ini 
      wget -O $${csgo}/addons/sourcemod/configs/deathmatch/deathmatch.ini $${github}/dm/deathmatch.ini 

  - path: /root/lgsm.cfg
    owner: root:root
    content: |
      
      ip={{ ds.meta_data.interfaces.public[0].ipv4.ip_address }}
      
      gametype="0"
      gamemode="1"

      mapgroup=""
      defaultmap=""

      maxplayers="10"
      tickrate="128"

      gslt="${csgo_gslt_token}"

      wsapikey="${csgo_web_token}"
      wscollectionid="134597451"

      updateonstart="on"

  - path: /root/csgoserver.cfg
    owner: root:root
    content: |
      rcon_password "${csgo_rcon_password}"

      hostname "dm.rdkr.uk"
      sv_tags "aim,deathmatch,dm,nobots,uk"

runcmd:
  - su - csgo -c "wget --no-clobber -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh csgoserver"
  - su - csgo -c "./csgoserver auto-install"
  - cp --preserve=mode /root/pre-start.sh /mnt/csgo/pre-start.sh
  - cp /root/csgoserver.cfg /mnt/csgo/serverfiles/csgo/cfg/
  - cp /root/lgsm.cfg /mnt/csgo/lgsm/config-lgsm/csgoserver/csgoserver.cfg
  - chown -R csgo:csgo /mnt/csgo
  - systemctl enable csgo
  - systemctl start csgo
