## template: jinja
#cloud-config 

fqdn: dm.rdkr.uk
hostname: dm.rdkr.uk

package_upgrade: true

write_files:
  - path: /home/csgo/pre-start.sh
    owner: csgo:csgo
    permissions: '0755'
    content: |
      #!/usr/bin/env sh

      wget -nc https://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git971-linux.tar.gz
      tar xfv mmsource-1.10.7-git971-linux.tar.gz -C serverfiles/csgo

      wget -nc https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6482-linux.tar.gz
      tar xfv sourcemod-1.10.0-git6482-linux.tar.gz -C serverfiles/csgo

      mv serverfiles/csgo/addons/sourcemod/plugins/nextmap.smx serverfiles/csgo/addons/sourcemod/plugins/disabled/
      mv serverfiles/csgo/addons/sourcemod/plugins/fun* serverfiles/csgo/addons/sourcemod/plugins/disabled

      wget -nc https://github.com/Maxximou5/csgo-deathmatch/releases/download/v2.0.9/deathmatch.zip
      unzip deathmatch.zip -d serverfiles/csgo/addons/sourcemod
      
      wget -nc -O quake.zip https://forums.alliedmods.net/attachment.php?attachmentid=125461&d=1380903530
      unzip quake.zip
      cp -r GameServer/* serverfiles/csgo
      rm -r FastDL/ GameServer/

      wget -nc -O quake.smx http://www.sourcemod.net/vbcompiler.php?file_id=155260
      mv quake.smx serverfiles/csgo/addons/sourcemod/plugins/

      csgo=/home/csgo/serverfiles/csgo
      github=https://raw.githubusercontent.com/rdkr/infra/master/csgo

      wget -O ${csgo}/cfg/gamemode_competitive_server.cfg ${github}/dm/gamemode_competitive_server.cfg
      wget -O ${csgo}/addons/sourcemod/configs/admins_simple.ini ${github}/admins_simple.ini 
      wget -O ${csgo}/addons/sourcemod/configs/deathmatch/deathmatch.ini ${github}/dm/deathmatch.ini
      wget -O ${csgo}/addons/sourcemod/configs/QuakeSetsList.cfg ${github}/dm/QuakeSetsList.cfg

  - path: /home/csgo/lgsm/config-lgsm/csgoserver/csgoserver.cfg
    owner: csgo:csgo
    content: |
      
      ip={% raw %}{{ ds.meta_data.interfaces.public[0].ipv4.ip_address }}{% endraw %}
      
      gametype="0"
      gamemode="1"

      mapgroup=""
      defaultmap=""

      maxplayers="10"
      tickrate="128"

      gslt="{{ env.CSGO_GSLT_TOKEN_DM }}"

      wsapikey="{{ env.CSGO_WEB_TOKEN_DM }}"
      wscollectionid="134597451"

      updateonstart="on"

      fn_parms(){
        parms="-game csgo -usercon -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +sv_setsteamaccount ${gslt} -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_type ${gametype} +game_mode ${gamemode} +host_workshop_collection ${wscollectionid} +workshop_start_map ${wsstartmap} -authkey ${wsapikey} -nobreakpad -nobots"
      }

  - path: /home/csgo/serverfiles/csgo/cfg/csgoserver.cfg 
    owner: csgo:csgo
    content: |
      rcon_password ""{{ env.CSGO_RCON_PASSWORD }}""
      hostname "dm.rdkr.uk"
      sv_tags "aim,deathmatch,dm,nobots,uk"

      host_info_show 2
      host_players_show 2

      sv_downloadurl "https://neel.rdkr.uk/csgo"

runcmd:
  - systemctl enable csgo
  - systemctl start csgo
