## template: jinja
#cloud-config

fqdn: pug.rdkr.uk
hostname: pug.rdkr.uk

users:
  - name: csgo
    lock_passwd: True
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

package_upgrade: true

write_files:
  - path: /home/csgo/pre-start.sh
    owner: csgo:csgo
    permissions: '0755'
    content: |
      #!/usr/bin/env sh

      ./csgoserver force-update

      csgo=/home/csgo/serverfiles/csgo
      github=https://raw.githubusercontent.com/rdkr/infra/master/csgo

      wget https://neel.rdkr.uk/csgo/pug.tar.gz
      tar xf pug.tar.gz -C $csgo

      wget -O ${csgo}/cfg/gamemode_competitive_server.cfg ${github}/pug/gamemode_competitive_server.cfg
      wget -O ${csgo}/addons/sourcemod/configs/admins_simple.ini ${github}/admins_simple.ini
      wget -O ${csgo}/gamemodes_server.txt ${github}/pug/gamemodes_server.txt

  - path: /home/csgo/lgsm/config-lgsm/csgoserver/csgoserver.cfg
    owner: csgo:csgo
    content: |

      ip={% raw %}{{ ds.meta_data.interfaces.public[0].ipv4.ip_address }}{% endraw %}

      gametype="0"
      gamemode="1"

      mapgroup="competitive"
      defaultmap="de_mirage"

      maxplayers="10"
      tickrate="128"

      gslt="{{ env.CSGO_GSLT_TOKEN_PUG }}"

      updateonstart="on"

  - path: /home/csgo/serverfiles/csgo/cfg/csgoserver.cfg
    owner: csgo:csgo
    content: |
      rcon_password "{{ env.CSGO_RCON_PASSWORD }}"
      sv_password "{{ env.CSGO_SV_PASSWORD }}"
      hostname "pug.rdkr.uk"

      host_info_show 2
      host_players_show 2

runcmd:
  - systemctl enable csgo
  - systemctl start csgo
