## template: jinja
#cloud-config

fqdn: dm.rdkr.uk
hostname: dm.rdkr.uk

package_upgrade: true

write_files:
  - path: /home/csgo/pre-start.sh
    owner: csgo:csgo
    permissions: '0755'
    content: |
      #!/usr/bin/env sh

      csgo=/home/csgo/serverfiles/csgo
      github=https://raw.githubusercontent.com/rdkr/infra/master/csgo

      /home/csgo/csgoserver force-update

      wget https://neel.rdkr.uk/csgo/dm.tar.gz
      tar xf dm.tar.gz -C $csgo

      wget -O ${csgo}/cfg/gamemode_competitive_server.cfg ${github}/dm/gamemode_competitive_server.cfg
      wget -O ${csgo}/addons/sourcemod/configs/admins_simple.ini ${github}/admins_simple.ini
      wget -O ${csgo}/addons/sourcemod/configs/deathmatch/deathmatch.ini ${github}/dm/deathmatch.ini
      wget -O ${csgo}/addons/sourcemod/configs/QuakeSetsList.cfg ${github}/dm/QuakeSetsList.cfg

  - path: /home/csgo/lgsm/config-lgsm/csgoserver/csgoserver.cfg
    owner: csgo:csgo
    content: |

      ip={% raw %}{{ ds.meta_data.interfaces.public[0].ipv4.ip_address }}{% endraw %}

      gametype="0"
      gamemode="1"

      mapgroup=""
      defaultmap=""

      maxplayers="10"
      tickrate="128"

      gslt="{{ env.CSGO_GSLT_TOKEN_DM }}"

      wsapikey="{{ env.CSGO_WEB_TOKEN_DM }}"
      wscollectionid="134597451"

      updateonstart="on"

      fn_parms(){
        parms="-game csgo -usercon -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +sv_setsteamaccount ${gslt} -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_type ${gametype} +game_mode ${gamemode} +host_workshop_collection ${wscollectionid} +workshop_start_map ${wsstartmap} -authkey ${wsapikey} -nobreakpad -nobots"
      }

  - path: /home/csgo/serverfiles/csgo/cfg/csgoserver.cfg
    owner: csgo:csgo
    content: |
      rcon_password ""{{ env.CSGO_RCON_PASSWORD }}""
      hostname "dm.rdkr.uk"
      sv_tags "aim,deathmatch,dm,nobots,uk"

      host_info_show 2
      host_players_show 2

      qs_headshot 0

      sv_downloadurl "https://neel.rdkr.uk/csgo"

runcmd:
  - systemctl enable csgo
  - systemctl start csgo
