---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
      - name: hermes
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hermes
  labels:
    app: hermes
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: hermes

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  resources:
    requests:
      memory: 256Mi
  serviceMonitorSelector:
    matchExpressions:
    - {key: app, operator: Exists}
---
apiVersion:  monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hermes
  labels:
    tier: hermes
spec:
  selector:
    matchLabels:
      tier: hermes
  endpoints:
  - port: hermes
    interval: 10s

---
apiVersion: v1
kind: Secret
metadata:
  name: sample-grafana-datasource
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus2
      type: prometheus
      access: proxy
      url: http://prometheus-operated:9090
      version: 1
      editable: false

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-server-conf
#   labels:
#     name: prometheus-server-conf
#   namespace: hermes
# data:
#   prometheus.yml: |-
#     global:
#         scrape_interval: 5s
#         scrape_timeout: 1s
#         evaluation_interval: 1m
#     scrape_configs:
#         - job_name: 'prometheus'
#           static_configs:
#           - targets: ['localhost:9090']
#         - job_name: 'hermes'
#           static_configs:
#           - targets: ['host.docker.internal:8080']
