---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
      - name: hermes
        image: rdkr/hermes:test
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: hermes
                key: DO_TOKEN
          - name: CSGO_GSLT_TOKEN_DM
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_GSLT_TOKEN_DM
          - name: CSGO_GSLT_TOKEN_PUG
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_GSLT_TOKEN_PUG
          - name: CSGO_WEB_TOKEN_DM
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_WEB_TOKEN_DM
          - name: CSGO_RCON_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_RCON_PASSWORD
          - name: CSGO_SV_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_SV_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: hermes
  labels:
    app: hermes
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: hermes

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testing123-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    # - host: testing123.example.com             # the domain you want associated
    - http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: hermes

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  resources:
    requests:
      memory: 256Mi
  serviceMonitorSelector:
    matchExpressions:
    - {key: app, operator: Exists}

---
apiVersion:  monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hermes
  labels:
    app: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  endpoints:
  - targetPort: 8080
    interval: 10s

---
apiVersion: v1
kind: Secret
metadata:
  name: sample-grafana-datasource
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus2
      type: prometheus
      access: proxy
      url: http://prometheus-operated:9090
      version: 1
      editable: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-grafana-dashboard
  labels:
     grafana_dashboard: "1"
data:
  k8s-dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "panels": [
        {
          "cacheTimeout": null,
          "content": "## confirmed game times\n* friday 24th, 1730-1900\n* saturday 25th, 1700-1900\n\n## potential game times\n* saturday 25th, day time, all generally available. please dm times\n* sunday 26th, any time, jon not available but pete has a ringer. please dm times",
          "datasource": null,
          "gridPos": {
            "h": 9,
            "w": 10,
            "x": 0,
            "y": 0
          },
          "id": 22,
          "links": [],
          "mode": "markdown",
          "timeFrom": null,
          "timeShift": null,
          "title": "game times",
          "type": "text"
        },
        {
          "content": "## server aliases\nadd these to your autoexec to type `pug` or `dm` to connect to that server\n\n```\npassword tbcuk2012\nalias dm connect dm.rdkr.uk\nalias pug connect pug.rdkr.uk\n```\n\n## binds\nadd these to your autoexec to hold `q` to noclip and to jumpthrow with `alt`\n\n```\n// noclip toggle\nalias +noclip \"noclip\"\nalias -noclip \"noclip\"\nbind \"q\" \"+noclip\"\n\n// jumpthrow bind\nalias \"+jumpthrow\" \"+jump;-attack\"\nalias \"-jumpthrow\" \"-jump\"\nbind \"ALT\" \"+jumpthrow\"\n```\n\n## rates\nadd these to your autoexec to ensure 128 tick rates where possible\n\n```\n// rates\ncl_interp \"0\"\ncl_interp_ratio \"1\"\ncl_cmdrate \"128\"\ncl_updaterate \"128\"\nrate \"128000\"\n```",
          "datasource": null,
          "gridPos": {
            "h": 19,
            "w": 14,
            "x": 10,
            "y": 0
          },
          "id": 20,
          "mode": "markdown",
          "timeFrom": null,
          "timeShift": null,
          "title": "info",
          "type": "text"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus2",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 10,
            "x": 0,
            "y": 9
          },
          "hiddenSeries": false,
          "id": 2,
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": true,
            "hideZero": false,
            "max": true,
            "min": true,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "connected",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "csgo_ping != -1",
              "interval": "",
              "legendFormat": "{{ name }}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "ping",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "s",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": "0",
              "show": true
            },
            {
              "format": "s",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus2",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 10,
            "x": 0,
            "y": 16
          },
          "hiddenSeries": false,
          "id": 16,
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": true,
            "hideZero": false,
            "max": true,
            "min": true,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "connected",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": true,
          "targets": [
            {
              "expr": "csgo_player_count != -1",
              "interval": "",
              "legendFormat": "{{ name }}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "players",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "decimals": 0,
              "format": "none",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": "0",
              "show": true
            },
            {
              "format": "s",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorPostfix": false,
          "colorPrefix": false,
          "colorValue": false,
          "colors": [
            "#299c46",
            "rgba(237, 129, 40, 0.89)",
            "#d44a3a"
          ],
          "datasource": "Prometheus2",
          "format": "none",
          "gauge": {
            "maxValue": 100,
            "minValue": 0,
            "show": false,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "gridPos": {
            "h": 4,
            "w": 4,
            "x": 10,
            "y": 19
          },
          "id": 17,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "maxPerRow": 2,
          "nullPointMode": "connected",
          "nullText": null,
          "pluginVersion": "6.7.3",
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "70%",
          "rangeMaps": [
            {
              "from": "-2",
              "text": "n/a",
              "to": "0"
            }
          ],
          "repeatDirection": "v",
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false,
            "ymax": null,
            "ymin": null
          },
          "tableColumn": "",
          "targets": [
            {
              "expr": "csgo_version{name=\"pug\"}",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "thresholds": "",
          "timeFrom": null,
          "timeShift": null,
          "title": "pug game version",
          "type": "singlestat",
          "valueFontSize": "100%",
          "valueMaps": [
            {
              "op": "=",
              "text": "n/a",
              "value": "-1"
            }
          ],
          "valueName": "current"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorPostfix": false,
          "colorPrefix": false,
          "colorValue": false,
          "colors": [
            "#299c46",
            "rgba(237, 129, 40, 0.89)",
            "#d44a3a"
          ],
          "datasource": "Prometheus2",
          "format": "none",
          "gauge": {
            "maxValue": 100,
            "minValue": 0,
            "show": false,
            "thresholdLabels": false,
            "thresholdMarkers": true
          },
          "gridPos": {
            "h": 4,
            "w": 4,
            "x": 14,
            "y": 19
          },
          "id": 18,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "maxPerRow": 2,
          "nullPointMode": "connected",
          "nullText": null,
          "pluginVersion": "6.7.3",
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "70%",
          "rangeMaps": [
            {
              "from": "-2",
              "text": "n/a",
              "to": "0"
            }
          ],
          "repeatDirection": "v",
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false,
            "ymax": null,
            "ymin": null
          },
          "tableColumn": "",
          "targets": [
            {
              "expr": "csgo_player_count{name=\"dm\"}",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "thresholds": "",
          "timeFrom": null,
          "timeShift": null,
          "title": "dm game version",
          "type": "singlestat",
          "valueFontSize": "100%",
          "valueMaps": [
            {
              "op": "=",
              "text": "n/a",
              "value": "-1"
            }
          ],
          "valueName": "current"
        }
      ],
      "schemaVersion": 22,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "csgo",
      "uid": "4rV0pyqZz",
      "variables": {
        "list": []
      },
      "version": 1
    }
