alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: false
server:
  persistentVolume:
    enabled: false
serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 5s
      scrape_timeout: 1s
      evaluation_interval: 1m
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'hermes'
      static_configs:
      - targets: ['host.docker.internal:8080']
