---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testing123-ingress
  namespace: networking
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: k8s.rdkr.uk
spec:
  rules:
  - host: k8s.rdkr.uk
  - http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
