{
 "title": "csgo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "pug current state",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(csgo_current{name=\"pug\"})"
    }
   ]
  },
  {
   "title": "dm current state",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(csgo_current{name=\"dm\"})"
    }
   ]
  },
  {
   "title": "players",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (name) (csgo_player_count)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "pug desired state",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(csgo_desired{name=\"pug\"})"
    }
   ]
  },
  {
   "title": "dm desired state",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(csgo_desired{name=\"dm\"})"
    }
   ]
  },
  {
   "title": "pug game version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(csgo_version{name=\"pug\"})"
    }
   ]
  },
  {
   "title": "dm game version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(csgo_version{name=\"dm\"})"
    }
   ]
  },
  {
   "title": "ping",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "avg by (name) (csgo_ping)", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "hermes uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "csgo_hermes_alive", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}