---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
      - name: hermes
        image: rdkr/hermes:test
        imagePullPolicy: Always
        command:
          - python
        args:
          - hermes_control.py
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: hermes
                key: DO_TOKEN
          - name: CSGO_GSLT_TOKEN_DM
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_GSLT_TOKEN_DM
          - name: CSGO_GSLT_TOKEN_PUG
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_GSLT_TOKEN_PUG
          - name: CSGO_WEB_TOKEN_DM
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_WEB_TOKEN_DM
          - name: CSGO_RCON_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_RCON_PASSWORD
          - name: CSGO_SV_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_SV_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: hermes
  labels:
    app: hermes
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: hermes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-discord
  namespace: hermes
spec:
  selector:
    matchLabels:
      app: hermes-discord
  replicas: 1
  template:
    metadata:
      labels:
        app: hermes-discord
    spec:
      containers:
      - name: hermes-discord
        image: rdkr/hermes:test
        imagePullPolicy: Always
        command:
          - python
        args:
          - hermes_discord.py
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: hermes
                key: CSGO_DISCORD_TOKEN
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: testing123-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     # - host: testing123.example.com             # the domain you want associated
#     - http:
#         paths:
#           - path: /
#             backend:
#               serviceName: grafana
#               servicePort: 3000



---
apiVersion:  monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hermes
  labels:
    app: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  endpoints:
  - targetPort: 8080
    interval: 10s
