name: minecraft-start
on: [workflow_dispatch]
defaults:
  run:
    working-directory: gcp/minecraft
env:
  TF_VAR_cloudflare_token: ${{ secrets.cloudflare_token }}
  TF_VAR_on: true
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.MINECRAFT_GITHUB_ACTIONS_KEY }}
          project_id: minecraft-rdkr-uk
      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.terraform_token }}
      - run: terraform init
      - run: terraform apply -auto-approve
